### ISSUE TITLE
Can not Dim lightbulbs

### ISSUE THREAD

**Issue by timgray** [Felixls/node-red-contrib-tplink-smarthome#1]
No documentation on how to dim or brighten a lightbulb.  

Is this even possible with this code?

**Comment by Felixls** [comment]
It's possible with the library but I did not implement that in this component yet.
Btw, I don't have lightbulb to test with, so I will need the help from someone that could test this node with bulbs.

**Comment by timgray** [comment]
I will absolutely be glad to help with testing.  I have 4 of the bulbs now that I am using the node.js command line tool  with right now.   I only have the  HB100 so setting hue and color temp I can not test, but brightness I can absolutely test.

**Comment by m-obi** [comment]
I have a LB110, so I can also test.

**Comment by felixls** [comment]
Thanks guys, merged.

**Comment by m-obi** [comment]
I solved this with msg.topic

[smart-bulb.txt](https://github.com/Felixls/node-red-contrib-tplink-smarthome/files/2041502/smart-bulb.txt)
