### ISSUE TITLE
Smart-Plug, Poll interval not respected

### ISSUE THREAD

**Issue by Brausmith** [Felixls/node-red-contrib-tplink-smarthome#3]
When subscribing to smart-plug events, the poll interval doesn't respect what is set in the node properties.
The interval is always 1000ms.
The plug model is HS110(AU).

**Comment by Felixls** [comment]
The parameter interval is only a ping to know if the device is alive.
I'll add another for the polling of the events.

**Comment by Brausmith** [comment]
Oh, ok thanks.

**Comment by Felixls** [comment]
Added on v0.1.1
